/// Flutter icons MedsReminder
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MedsReminder
///      fonts:
///       - asset: fonts/MedsReminder.ttf
///
/// 
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
///
import 'package:flutter/widgets.dart';

class MedsReminder {
  MedsReminder._();

  static const _kFontFam = 'MedsReminder';
  static const String? _kFontPkg = null;

  static const IconData minus_circle = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_circle = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_circle = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
